// Column-complete fate of every Postgres column, from the official DDLs
// (verifier-alliance/database-specs database.sql + argotorg/sourcify migrations).
// kind: attr | payload | entity | key | folded | composed | internal | derived
export const COLMAP = {
  contract_deployments: { t: "contract_deployments → verified_contract", n: "The deployment identity becomes typed, indexed attributes — which is what makes them filterable. The id is the entity key.", r: [
    ["id", "key", "the verified_contract entity key", "identity of the row = identity of the entity"],
    ["chain_id", "attr", "chainid (u64)", "numeric → range queries"],
    ["address", "attr", "address (addr) + chainaddr (str)", "the primary lookup"],
    ["transaction_hash", "payload", "payload.deployment.transactionHash", "returned, never filtered on"],
    ["block_number", "attr", "blocknumber (u64) + payload.deployment", "ranges"],
    ["transaction_index", "payload", "payload.deployment.transactionIndex", ""],
    ["deployer", "attr", "deployer (addr) + payload.deployment", "“everything this deployer shipped”"],
    ["contract_id", "folded", "→ contracts → the two code-hash attrs", "a FK into a pure join table"],
    ["created_at", "internal", "—", "audit column; not served by the public API"],
    ["updated_at", "internal", "—", "audit column; not served by the public API"],
    ["created_by", "internal", "—", "audit column; not served by the public API"],
    ["updated_by", "internal", "—", "audit column; not served by the public API"],
  ]},
  verified_contracts: { t: "verified_contracts → verified_contract", n: "The central link IS the entity — one per (chain, address). Sourcify's API folds each match boolean pair into one string; the audit columns never leave their Postgres.", r: [
    ["id", "internal", "—", "internal id; the public matchId comes from sourcify_matches.id"],
    ["deployment_id", "key", "the entity itself", "this row *is* the deployment↔compilation link"],
    ["compilation_id", "key", "compilationref (key attr)", "the foreign key as a native pointer → compilation entity"],
    ["creation_match", "folded", "creationmatch (str)", "true+metadata → exact_match · true → match · false → null — the API's own folding"],
    ["creation_metadata_match", "folded", "creationmatch (str)", "folded with creation_match"],
    ["creation_transformations", "payload", "payload.creationTransformations", "served in creationBytecode.transformations"],
    ["creation_values", "payload", "payload.creationTransformationValues", "served in creationBytecode.transformationValues"],
    ["runtime_match", "folded", "runtimematch (str)", "same folding"],
    ["runtime_metadata_match", "folded", "runtimematch (str)", "folded with runtime_match"],
    ["runtime_transformations", "payload", "payload.runtimeTransformations", "served in runtimeBytecode.transformations"],
    ["runtime_values", "payload", "payload.runtimeTransformationValues", "served in runtimeBytecode.transformationValues"],
    ["created_at", "internal", "—", "audit; the public verifiedAt is sourcify_matches.created_at"],
    ["updated_at", "internal", "—", "audit column; not served by the public API"],
    ["created_by", "internal", "—", "audit column; not served by the public API"],
    ["updated_by", "internal", "—", "audit column; not served by the public API"],
  ]},
  sourcify_matches: { t: "sourcify_matches → two places", n: "Sourcify's own table on top of the Verifier Alliance schema. Identity numbers stay on the contract; the metadata JSON moves to the compilation, where it deduplicates.", r: [
    ["id", "attr", "matchid (u64)", "the public matchId — the cursor Sourcify pages by"],
    ["verified_contract_id", "key", "the verified_contract entity", "1:1 with the link row"],
    ["creation_match", "attr", "creationmatch (str)", "the public string (exact_match / match / null)"],
    ["runtime_match", "attr", "runtimematch (str)", "the public string"],
    ["created_at", "attr", "verifiedat (u64)", "the public verifiedAt — date ranges"],
    ["metadata", "payload", "compilation payload.metadata", "identical for every contract sharing the compilation — stored once; JSON.stringify reproduces the compiler's string byte-for-byte"],
    ["updated_at", "internal", "—", "audit column; not served by the public API"],
  ]},
  contracts: { t: "contracts → folded into verified_contract", n: "A pure join table needs no entity of its own — its two real columns become two attributes.", r: [
    ["id", "folded", "—", "referenced by contract_deployments.contract_id; no entity needed"],
    ["creation_code_hash", "attr", "creationcodehash (str)", "join into the code lane"],
    ["runtime_code_hash", "attr", "runtimecodehash (str)", "“every deployment of this exact bytecode”"],
    ["created_at", "internal", "—", "audit column; not served by the public API"],
    ["updated_at", "internal", "—", "audit column; not served by the public API"],
    ["created_by", "internal", "—", "audit column; not served by the public API"],
    ["updated_by", "internal", "—", "audit column; not served by the public API"],
  ]},
  compiled_contracts: { t: "compiled_contracts → compilation (+ code)", n: "Deduplicated by a CONTENT fingerprint over inputs AND outputs — v1's weaker key conflated 99 distinct compilations on this chain.", r: [
    ["id", "key", "the compilation entity key", "pointed at by compilationref"],
    ["compiler", "attr", "compiler (str), echoed on the contract", "filterable"],
    ["version", "attr", "compilerversion (str), echoed on the contract", "startsWith('0.8.') across a minor line"],
    ["language", "attr", "language (str), echoed on the contract", "Solidity / Vyper"],
    ["name", "attr", "name (str), echoed on the contract", "prefix search"],
    ["fully_qualified_name", "payload", "payload.fullyQualifiedName", "path:Name; 128-byte attr cap would truncate it"],
    ["compiler_settings", "payload", "payload.compilerSettings (+ attrs optimizer, optimizerruns, evmversion)", "settings lifted to filters"],
    ["compilation_artifacts", "payload", "abi → contract payload · userdoc, devdoc, storageLayout, sourceIds → compilation payload", "abi rides the hot path"],
    ["creation_code_hash", "entity", "payload.recompiledCreationHash → code entity", "recompiled creation bytecode, content-addressed"],
    ["creation_code_artifacts", "payload", "payload.creationCodeArtifacts", "sourceMap, linkReferences, cborAuxdata"],
    ["runtime_code_hash", "entity", "payload.recompiledRuntimeHash → code entity", "recompiled runtime bytecode"],
    ["runtime_code_artifacts", "payload", "payload.runtimeCodeArtifacts", "sourceMap, linkReferences, immutableReferences, cborAuxdata"],
    ["additional_input", "payload", "contract payload.additionalInput", "the API field; null on every Unichain contract"],
    ["created_at", "internal", "—", "audit column; not served by the public API"],
    ["updated_at", "internal", "—", "audit column; not served by the public API"],
    ["created_by", "internal", "—", "audit column; not served by the public API"],
    ["updated_by", "internal", "—", "audit column; not served by the public API"],
  ]},
  compiled_contracts_sources: { t: "compiled_contracts_sources → the path→hash map", n: "Attributes cap at 32 and a compilation can reference 93 files, so the join is a small map on the compilation payload — exactly how Sourcify's table references into its deduplicated sources.", r: [
    ["id", "folded", "—", "no entity; the row is one entry of a map"],
    ["compilation_id", "folded", "the compilation that carries the map", "implicit"],
    ["path", "payload", "a key of payload.sources", "path → sha256"],
    ["source_hash", "payload", "a value of payload.sources", "the sourcefile entity's address"],
    ["created_at", "internal", "—", "audit column; not served by the public API"],
  ]},
  sources: { t: "sources → sourcefile (+ blob for the tail)", n: "One entity per UNIQUE file body — OpenZeppelin's ERC20.sol exists on-chain exactly once.", r: [
    ["source_hash", "attr", "hash (str, sha256)", "what readers query by"],
    ["source_hash_keccak", "derived", "—", "derivable from content; not stored"],
    ["content", "payload", "sourcefile payload.content (→ blob parts when > ~123 KB)", "45.4 MB across 6,119 unique files; 40 spill"],
    ["created_at", "internal", "—", "audit column; not served by the public API"],
    ["updated_at", "internal", "—", "audit column; not served by the public API"],
    ["created_by", "internal", "—", "audit column; not served by the public API"],
    ["updated_by", "internal", "—", "audit column; not served by the public API"],
  ]},
  code: { t: "code → code", n: "The most direct translation: content-addressed bytecode on both sides. A factory's clones collapse to one entity.", r: [
    ["code_hash", "derived", "—", "sha256 PK; we address by keccak — derivable from the bytes"],
    ["code_hash_keccak", "attr", "hash (str, keccak)", "chain-native address"],
    ["code", "payload", "raw bytes (octet-stream)", "half the bytes of hex"],
    ["created_at", "internal", "—", "audit column; not served by the public API"],
    ["updated_at", "internal", "—", "audit column; not served by the public API"],
    ["created_by", "internal", "—", "audit column; not served by the public API"],
    ["updated_by", "internal", "—", "audit column; not served by the public API"],
  ]},
  signatures: { t: "signatures → signature", n: "One entity per selector — the best-shaped workload here (86-byte median payload, one equality).", r: [
    ["signature_hash_4", "attr", "selector (str)", "the lookup key"],
    ["signature_hash_32", "payload", "payload · per candidate", "collisions are real, the whole set is stored"],
    ["signature", "payload", "payload · candidate text", ""],
    ["created_at", "internal", "—", "audit column; not served by the public API"],
  ]},
  compiled_contracts_signatures: { t: "compiled_contracts_signatures → derived", n: "Not stored: the signatures field is recomputed from the ABI at read time — Sourcify composes it too.", r: [
    ["id", "derived", "—", "no row needed"],
    ["compilation_id", "derived", "—", "the ABI on the contract already says which"],
    ["signature_hash_32", "derived", "keccak over the canonical text, at read time", "measured identical as sets, 120/120"],
    ["signature_type", "derived", "function / event / error, from the ABI entry", ""],
    ["created_at", "internal", "—", "audit column; not served by the public API"],
  ]},
};

// totals, for the UI caption
let total = 0, by = {};
for (const t of Object.values(COLMAP)) for (const [, k] of t.r) { total++; by[k] = (by[k] ?? 0) + 1; }
export const COLSTATS = { total, by };
if (process.argv[1] && process.argv[1].endsWith("colmap.mjs")) console.log(total, by);
